"""Add email must be unique

Revision ID: d2daf636c00e
Revises: 4b41936074d6
Create Date: 2025-08-11 00:31:45.711172

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2daf636c00e"
down_revision: Union[str, Sequence[str], None] = "4b41936074d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "contacts", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="unique")
    # ### end Alembic commands ###
